/* 
 * Barcode
 *
 * <b>The Barcode Reader API '/reader' reads barcodes from image files and returns the barcode data as JSON files.</b>    The flow is generally as follows:  1. First upload an image using the /reader POST endpoint. You will get back a job response that contains a job with its associated settings.  2. Start the job from a PUT request to the /reader/{jobid} endpoint, with the Job and Settings JSON as request body. The barcode detection will now start.  3. Check the job status from the /reader/{jobid} GET endpoint until the status has changed to DONE or ERROR. Messaging using a websocket will be available as an alternative in a future version  4. Retrieve the JSON file using the /reader/{jobid}/stream GET endpoint. This will return the JSON file only when the status is DONE. In other cases it will return the Job Response JSON (with http code 202 instead of 200)      <b>Interactive testing: </b>A web based test console is available in the <a href=\"https://store.sphereon.com\">Sphereon API Store</a>
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Sphereon.SDK.Barcode.Client;
using Sphereon.SDK.Barcode.Api;
using Sphereon.SDK.Barcode.Model;

namespace Sphereon.SDK.Barcode.Test
{
    /// <summary>
    ///  Class for testing BarcodeReaderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BarcodeReaderApiTests
    {
        private BarcodeReaderApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BarcodeReaderApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BarcodeReaderApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BarcodeReaderApi
            //Assert.IsInstanceOfType(typeof(BarcodeReaderApi), instance, "instance is a BarcodeReaderApi");
        }

        
        /// <summary>
        /// Test DeleteJob
        /// </summary>
        [Test]
        public void DeleteJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobid = null;
            //var response = instance.DeleteJob(jobid);
            //Assert.IsInstanceOf<ReaderJobResponse> (response, "response is ReaderJobResponse");
        }
        
        /// <summary>
        /// Test GetJob
        /// </summary>
        [Test]
        public void GetJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobid = null;
            //var response = instance.GetJob(jobid);
            //Assert.IsInstanceOf<ReaderResultJobResponse> (response, "response is ReaderResultJobResponse");
        }
        
        /// <summary>
        /// Test SubmitJob
        /// </summary>
        [Test]
        public void SubmitJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobid = null;
            //ReaderJob job = null;
            //var response = instance.SubmitJob(jobid, job);
            //Assert.IsInstanceOf<ReaderJobResponse> (response, "response is ReaderJobResponse");
        }
        
        /// <summary>
        /// Test UploadFile
        /// </summary>
        [Test]
        public void UploadFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream stream = null;
            //var response = instance.UploadFile(stream);
            //Assert.IsInstanceOf<ReaderJobResponse> (response, "response is ReaderJobResponse");
        }
        
    }

}
